name: "Install Flutter"
author: Britannio Jarrett
description: "Installs Flutter(https://flutter.dev)"
inputs:
  version:
    description: "The channel/version of Flutter to be used e.g., beta or 2.0.0"
    required: false
    default: "stable"
runs:
  using: "composite"
  steps:
    - run: |
        echo "Installing Flutter from ${{ inputs.version }}"
        git clone https://github.com/flutter/flutter.git --depth 1 -b ${{ inputs.version }} "$HOME/flutter"
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      shell: bash
    - run: flutter precache
      shell: bash
branding:
  icon: "smartphone"
  color: "purple"
