name: Comparison
on:
  pull_request:
  push:

jobs:
  comparison-britannio-action-install-flutter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        flutter_version: [stable, master]
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          flutter-version: stable
      - run: flutter --version
  comparison-subosito-flutter-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        flutter_version: [stable, master]
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter --version
